// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types based on our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          name: string
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          created_at?: string
          updated_at?: string
        }
      }
      artists: {
        Row: {
          id: string
          name: string
          slug: string
          template_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          template_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          template_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tracks: {
        Row: {
          id: string
          name: string
          key: string
          artist_id: string
          template_id: string | null
          track_status_id: string | null
          step_id: string | null
          tempo: number | null
          minutes: number | null
          seconds: number | null
          samples: string
          album_id: string | null
          album_order: number | null
          date_created: string | null
          isrc_code: string | null
          live_ready: boolean
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
        }
        Insert: {
          id?: string
          name: string
          key: string
          artist_id: string
          template_id?: string | null
          track_status_id?: string | null
          step_id?: string | null
          tempo?: number | null
          minutes?: number | null
          seconds?: number | null
          samples?: string
          album_id?: string | null
          album_order?: number | null
          date_created?: string | null
          isrc_code?: string | null
          live_ready?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
        Update: {
          id?: string
          name?: string
          key?: string
          artist_id?: string
          template_id?: string | null
          track_status_id?: string | null
          step_id?: string | null
          tempo?: number | null
          minutes?: number | null
          seconds?: number | null
          samples?: string
          album_id?: string | null
          album_order?: number | null
          date_created?: string | null
          isrc_code?: string | null
          live_ready?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
      }
      user_artists: {
        Row: {
          id: string
          user_id: string
          artist_id: string
          role: 'owner' | 'collaborator'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          artist_id: string
          role?: 'owner' | 'collaborator'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          artist_id?: string
          role?: 'owner' | 'collaborator'
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}



